import { ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import solinLogo from '@/assets/solin-logo.png';

export default function TermsOfService() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="mx-auto max-w-2xl px-4 py-8">
        <button
          onClick={() => navigate(-1)}
          className="mb-6 flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          Back
        </button>

        <div className="flex flex-col items-center mb-8">
          <img src={solinLogo} alt="SOLIN" className="w-12 h-12 rounded-xl mb-3" />
          <h1 className="text-2xl font-semibold text-foreground">Terms of Service</h1>
          <p className="text-sm text-muted-foreground mt-1">Last updated: April 2026</p>
        </div>

        <div className="space-y-8 text-sm leading-relaxed text-foreground/80">
          <Section title="1. Acceptance of Terms">
            <p>
              By accessing or using SOLIN, you agree to be bound by these Terms of Service. If you do not
              agree to these terms, please do not use the service. We may update these terms from time to
              time and will notify users of significant changes.
            </p>
          </Section>

          <Section title="2. Description of Service">
            <p>
              SOLIN is an AI companion application that provides AI-powered conversations across multiple
              personas. It is designed for emotional support and companionship through artificial intelligence.
            </p>
            <p className="mt-2 font-semibold text-[#FFD700]">
              SOLIN is NOT a substitute for professional mental health support, medical advice, therapy,
              or crisis intervention services.
            </p>
          </Section>

          <Section title="3. Account Registration">
            <ul className="list-disc pl-5 space-y-2">
              <li>You must provide accurate and complete information when creating an account.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>You must be at least 13 years old to use the service.</li>
              <li>One account per person — do not create multiple accounts.</li>
            </ul>
          </Section>

          <Section title="4. Subscription and Payments">
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Free tier:</strong> 20 messages per day across all companions.</li>
              <li><strong>Premium subscription:</strong> Unlimited messages and all premium features.</li>
              <li>Payments are processed securely by Dodo Payments.</li>
              <li>Subscriptions renew automatically unless cancelled before the renewal date.</li>
              <li><strong>Refunds:</strong> Contact pk9829922@gmail.com within 7 days of a charge for a refund.</li>
              <li>Prices may change with 30 days' notice to active subscribers.</li>
            </ul>
          </Section>

          <Section title="5. Acceptable Use">
            <p>You agree to:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Use the service only for lawful purposes.</li>
              <li>Not attempt to manipulate, jailbreak, or exploit the AI.</li>
              <li>Not use the service to generate harmful, illegal, or abusive content.</li>
              <li>Not share your account credentials with others.</li>
              <li>Not use automated systems, bots, or scripts to access the service.</li>
              <li>Not create multiple accounts to circumvent free message limits.</li>
            </ul>
          </Section>

          <Section title="6. AI Companion Disclaimer">
            <div className="rounded-xl bg-secondary p-4 space-y-2">
              <p>⚠️ <strong>Important:</strong></p>
              <ul className="list-disc pl-5 space-y-2">
                <li>SOLIN AI companions are <strong>not real people</strong>.</li>
                <li>All responses are generated by artificial intelligence and may occasionally be inaccurate or inappropriate.</li>
                <li>Do <strong>not</strong> rely on this service for medical, legal, or financial advice.</li>
                <li>If you are in crisis, please contact emergency services or a mental health professional immediately.</li>
              </ul>
            </div>
          </Section>

          <Section title="7. Intellectual Property">
            <ul className="list-disc pl-5 space-y-2">
              <li>SOLIN and all its content, design, and branding are owned by Prasad Kumar.</li>
              <li>You retain ownership of your own conversation content.</li>
              <li>You grant us a limited license to process your content solely to provide the service.</li>
            </ul>
          </Section>

          <Section title="8. Privacy">
            <p>
              Your use of the service is governed by our{' '}
              <a href="/privacy-policy" className="text-primary hover:underline">Privacy Policy</a>,
              which describes how we collect, use, and protect your data.
            </p>
          </Section>

          <Section title="9. Termination">
            <ul className="list-disc pl-5 space-y-2">
              <li>We may suspend or terminate accounts that violate these terms.</li>
              <li>You may delete your account at any time from your profile settings.</li>
              <li>Upon termination, your data will be deleted in accordance with our Privacy Policy.</li>
            </ul>
          </Section>

          <Section title="10. Limitation of Liability">
            <p>
              SOLIN is provided "as is" without warranties of any kind, express or implied. We are not
              liable for any direct, indirect, incidental, or consequential damages arising from your
              use of the service. Our maximum liability is limited to the amount you have paid us in the
              last 3 months.
            </p>
          </Section>

          <Section title="11. Governing Law">
            <p>
              These terms are governed by applicable law. Any disputes arising from the use of SOLIN
              shall be resolved through binding arbitration.
            </p>
          </Section>

          <Section title="12. Contact">
            <p>
              For questions about these terms, contact us at:{' '}
              <a href="mailto:pk9829922@gmail.com" className="text-primary hover:underline">
                pk9829922@gmail.com
              </a>
            </p>
          </Section>
        </div>

        <footer className="mt-12 border-t border-border pt-6 pb-8 text-center text-xs text-muted-foreground space-y-2">
          <p>© {new Date().getFullYear()} SOLIN. All rights reserved.</p>
          <div className="flex justify-center gap-4">
            <a href="/privacy-policy" className="hover:text-foreground transition-colors">Privacy Policy</a>
            <a href="/terms-of-service" className="hover:text-foreground transition-colors">Terms of Service</a>
          </div>
        </footer>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-lg font-semibold text-foreground mb-3">{title}</h2>
      {children}
    </section>
  );
}
